services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docuparse-backend
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Re-add full directory mount for hot-reloading
      - ./backend:/app
      - ./README.md:/app/README.md # Mount the root README.md
      - ./.cursor:/root/.cursor # Mount .cursor directory
      - ./.gitignore:/app/.gitignore # Mount .gitignore
    env_file:
      - ./backend/.env # Load environment variables from backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docuparse-frontend
    ports:
      - "8501:8501" # Map host port 8501 to container port 8501
    volumes:
      # Re-add full directory mount for hot-reloading
      - ./frontend:/app
      - ./README.md:/app/README.md # Mount the root README.md
      - ./.cursor:/root/.cursor # Mount .cursor directory
      - ./.gitignore:/app/.gitignore # Mount .gitignore
    env_file:
      - ./frontend/.env # Load environment variables from frontend/.env
    depends_on:
      - backend # Wait for the backend service to start
    environment:
      # Ensure Streamlit can reach the backend service via its service name
      - BACKEND_URL=http://backend:8000

# Keep volumes for secrets/db if they exist
# volumes: ...
# secrets: ...

# Optional: Add healthcheck if needed for depends_on
# healthcheck:
#   test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
#   interval: 30s
#   timeout: 10s
#   retries: 3
#   start_period: 40s

# Optional: Add restart policy
# restart: unless-stopped 