name: docuparse-backend
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - fastapi
  - uvicorn[standard]
  - pydantic
  - python-dotenv
  - pip:
    - pymupdf
    # - pdfplumber # Alternative if needed

  # Potential future dependencies
  # - celery # For async tasks
  # - redis-py # For Celery broker/backend
  # Development/Testing
  # - pytest
  # - httpx # For testing FastAPI endpoints